# Generated by Django 4.2.6 on 2023-11-07 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Requete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=100)),
                ('department', models.CharField(choices=[('rh', 'HR'), ('technique', 'Network'), ('sales', 'Commercial & Marketing'), ('finance', 'Finance')], default='sales', max_length=30)),
                ('project_code', models.CharField()),
                ('type_service', models.CharField(choices=[('installation', 'Installation'), ('service_repair', 'Service/Repair'), ('transfer', 'Transfer'), ('sale', 'Sale')], default='installation', max_length=20)),
                ('customer', models.CharField()),
                ('location', models.CharField()),
                ('date_de_creation', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager_signature', models.CharField(choices=[('test', 'Test')], default='test', max_length=50)),
                ('line_manager_name', models.CharField(choices=[('test', 'Test')], default='test', max_length=50)),
                ('items_recieved_name', models.CharField(max_length=50)),
                ('items_recieved_signature', models.CharField(max_length=50)),
                ('issued_name', models.CharField(choices=[('test', 'Test')], default='test', max_length=50)),
                ('issued_signature', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('v', 'valide'), ('n', 'non valide')], default='n', max_length=30)),
                ('delivery', models.CharField(choices=[('y', 'yes'), ('n', 'no')], default='n', max_length=30)),
                ('user', models.ForeignKey(default=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
